Translated "KubeKey" from EN to ZH
kubesphere/website pull request #1140
Opened 2021-03-03 08:19 UTC by adakisme

Signed-off-by: adakisme <571414446@qq.com>

2021-03-03 08:33 UTC, LinuxSuRen requested changes
thanks for your contribution. I left some comments.

2021-03-03 08:33 UTC, LinuxSuRen commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +- 括缩集群；
`括` or `扩`

2021-03-03 08:33 UTC, LinuxSuRen commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +准备好配置文件后，您将使用带有不同标志的 `./kk` 命令来进行不同的操作。这之后，KubeKey 会自动安装 Docker，并拉取所有必要的镜像以进行安装。安装完成后，您还可以检查安装日志。
`标志`
根据上下文，这里应该是`参数`

2021-03-03 08:33 UTC, LinuxSuRen commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +{{< tab "P如果您访问 GitHub/Googleapis受限" >}}
`P如果` or `如果`

2021-03-03 08:33 UTC, LinuxSuRen commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +{{< tab "P如果您访问 GitHub/Googleapis受限" >}}
`Googleapis受限` should be `Googleapis 受限`

2021-03-03 10:09 UTC, Sherlock113 reviewed
Have a look at my comments and make changes.

2021-03-03 10:09 UTC, Sherlock113 commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +准备好配置文件后，您将使用带有不同标志的 `./kk` 命令来进行不同的操作。这之后，KubeKey 会自动安装 Docker，并拉取所有必要的镜像以进行安装。安装完成后，您还可以检查安装日志。
您将使用带有不同标志的 ./kk 命令来进行不同的操作
->
您需要使用 `./kk` 命令以及不同的标志来进行不同的操作

2021-03-03 10:09 UTC, Sherlock113 commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +- KubeKey 支持多种安装选项，例如[all-in-one](../../../quick-start/all-in-one-on-linux/)，[多节点安装](../multioverview/)，以及[离线安装](../air-gapped-installation/).
KubeKey 支持多种安装选项，例如[all-in-one](../../../quick-start/all-in-one-on-linux/)，[多节点安装](../multioverview/)，以及[离线安装](../air-gapped-installation/).
->
KubeKey 支持多种安装选项，例如 [All-in-One](../../../quick-start/all-in-one-on-linux/)、[多节点安装](../multioverview/)以及[离线安装](../air-gapped-installation/)。

Never use the English period at the end of a Chinese sentence.

2021-03-03 10:09 UTC, Sherlock113 commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +{{< tab "P如果您访问 GitHub/Googleapis受限" >}}
P如果您访问 GitHub/Googleapis受限
->
如果您访问 GitHub/Googleapis 受限

2021-03-03 10:09 UTC, Sherlock113 commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +从[GitHub Release Page](https://github.com/kubesphere/kubekey/releases)下载 KubeKey 或者直接运行以下命令。
从[GitHub Release Page](https://github.com/kubesphere/kubekey/releases)下载 KubeKey 或者直接运行以下命令。
->
从 [GitHub Release Page](https://github.com/kubesphere/kubekey/releases) 下载 KubeKey 或者直接运行以下命令。

2021-03-03 10:09 UTC, Sherlock113 commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +下载 KubeKey 之后，如果您将其转移到访问 Googleapis 受限的新机器上，就必须再次运行 `export KKZONE=cn`，然后继续执行以下步骤。
就必须再次运行
->
请务必再次运行

2021-03-03 10:09 UTC, Sherlock113 commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +通过以上的命令，可以下载 KubeKey 的最新发布 (v1.0.1) 。您可以更改命令中的版本号来下载特定的版本。
通过以上的命令，可以下载 KubeKey 的最新发布 (v1.0.1) 。您可以更改命令中的版本号来下载特定的版本。
->
通过以上的命令，可以下载 KubeKey 的最新版本 (v1.0.1)。您可以更改命令中的版本号来下载特定的版本。

2021-03-04 03:54 UTC, Sherlock113 commented on content/zh/docs/installing-on-linux/introduction/kubekey.md
> +- KubeKey 支持多种安装选项，例如 [All-in-One](../../../quick-start/all-in-one-on-linux/)、[多节点安装](../multioverview/)以及[离线安装](../air-gapped-installation/).
Change the period at the end of this sentence.

2021-03-04 04:05 UTC, merged