aliyun-ack-en translated
kubesphere/website pull request #1236
Opened 2021-03-25 06:40 UTC by serenashe

Signed-off-by: adakisme <serenashe@yunify.com>

2021-03-25 09:57 UTC, Felixnoo requested changes

2021-03-25 09:57 UTC, Felixnoo commented on content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
> +3. 访问**自定义资源 CRD**，在搜索栏输入  `ClusterConfiguration`，然后按下键盘上的**回车键**。点击 **ClusterConfiguration** 访问其详情页。
Delete the extra space between 输入 and `ClusterConfiguration`

2021-03-25 10:04 UTC, Felixnoo commented
/lgtm

2021-03-25 13:19 UTC, Sherlock113 commented on content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
>  titleLink: "Import an Aliyun ACK Cluster"
Translate the value of this three lines

2021-03-26 02:03 UTC, Sherlock113 commented
Merge these five commits please. Use `git log` to check your commit history.

2021-03-26 02:51 UTC, Sherlock113 commented
Please submit this pr to the release-3.0 branch as well.

2021-03-26 02:51 UTC, merged