aws-gke-en translated
kubesphere/website pull request #1248
Opened 2021-03-26 06:08 UTC by serenashe

Signed-off-by: adakisme <serenashe@yunify.com>

2021-03-26 08:52 UTC, Felixnoo requested changes
Please update per my comments, thanks.

2021-03-26 08:52 UTC, Felixnoo commented on content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
> +1. 为了通过 Host 集群管理 Member 集群，您需要使它们之间的 `jwtSecret` 相同。首先，需要在 Host 集群上执行以下命令获取 `jwtSecret`。首先，需要在 Host 集群上执行以下命令获取 `jwtSecret`。
Delete the extra sentence: 首先，需要在 Host 集群上执行以下命令获取 `jwtSecret`。

2021-03-26 08:52 UTC, Felixnoo commented on content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
> +3. 运行以下命令检索新的 kubeconfig 文件：
检索 -> 获取

2021-03-26 08:52 UTC, Felixnoo commented on content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
> +   输出类似如下，可以看到插入了新用户 `kubesphere` 并已将其设置为了当前集群环境上下文用户：
插入了 -> 已插入
设置为了 -> 设置为

2021-03-29 07:42 UTC, Felixnoo commented
/lgtm

2021-03-29 08:03 UTC, Sherlock113 commented on content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
> +   输出类似如下，可以看到已插入新用户 `kubesphere` 并已将其设置为当前集群环境上下文用户：
上下文用户
->
上下文 (current-context) 用户

2021-03-29 08:03 UTC, Sherlock113 commented on content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
>  keywords: 'Kubernetes, KubeSphere, 多集群, Amazon eks'
Amazon eks
->
Amazon EKS

2021-03-29 08:27 UTC, merged