Translated data-migration-during-upgrade
kubesphere/website pull request #1341
Opened 2021-04-12 06:31 UTC by serenashe

Signed-off-by: adakisme <serenashe@yunify.com>

2021-04-12 08:15 UTC, Felixnoo requested changes
Please take a look at my comments, thanks.

2021-04-12 08:15 UTC, Felixnoo commented on content/zh/docs/upgrade/devops-data-migration-upgrade.md
> +将 KubeSphere 从 v2.1 升级到 v3.0 时，可能会遇到主要由 DevOps 架构发生变化而引发的问题。本文档介绍 DevOps 架构的变化以及数据迁移的方案和风险。
可能会遇到主要由 DevOps 架构发生变化而引发的问题
->
在 DevOps 中可能遇到的问题主要是因其架构发生了变化

2021-04-12 08:15 UTC, Felixnoo commented on content/zh/docs/upgrade/devops-data-migration-upgrade.md
> +### 通过任务迁移
任务迁移 -> 任务 (Job) 迁移

2021-04-12 09:12 UTC, Felixnoo commented
/lgtm

2021-04-13 02:10 UTC, Sherlock113 commented on content/zh/docs/upgrade/devops-data-migration-upgrade.md
> +description: "了解升级 KubeSphere DevOps 时的数据迁移及其风险."
及其风险.
->
及其风险。

2021-04-13 03:36 UTC, Sherlock113 commented
/lgtm

2021-04-13 03:36 UTC, merged