kubesphere-3.1.0-ga-announcement.md
kubesphere/website pull request #1487
Opened 2021-04-30 17:44 UTC by faweizhao26

Signed-off-by: faweizhao26 <faweizhao@yunify.com>

2021-05-01 04:27 UTC, LinuxSuRen requested changes
Thanks for the great news. I left some comments, please have a look at it.

2021-05-01 04:27 UTC, LinuxSuRen commented on content/zh/blogs/kubesphere-3.1.0-ga-announcement.md
> +<iframe width="760" height="380" src="//player.bilibili.com/player.html?aid=972796031&bvid=BV1qp4y1b7Jz&cid=331391855&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscre
![image](https://user-images.githubusercontent.com/1450685/116770725-51329900-aa78-11eb-9e25-08a2ee2ed394.png)

It looks like it does not work well here.

2021-05-01 13:11 UTC, FeynmanZhou commented on content/zh/blogs/kubesphere-3.1.0-ga-announcement.md
> +![](https://cdn.jsdelivr.net/gh/yangchuansheng/imghosting1@main/img/20210429141959.png)
Add the file name in `![xxx]`

2021-05-01 13:13 UTC, FeynmanZhou commented on content/zh/blogs/kubesphere-3.1.0-ga-announcement.md
> +![](https://cdn.jsdelivr.net/gh/yangchuansheng/imghosting@three/img/20210428221044.png)
Please do not use personal CDN storage. You can store these images in this repository or our QingStor Object Storage.

2021-05-07 07:37 UTC, FeynmanZhou commented
/lgtm

2021-05-07 07:37 UTC, FeynmanZhou approved these changes

2021-05-07 07:37 UTC, merged