Second task
kubesphere/website pull request #1872
Opened 2021-08-08 16:31 UTC by YANGMAO-ZHANG

@Felixnoo 
# 1854

2021-08-09 07:04 UTC, Felixnoo requested changes
Please take a look at my comments, thanks.

2021-08-09 07:04 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
> +2. 创建 Inbound Security 规则以允许网络安全组中的 Internet 访问。
`创建 Inbound Security 规则以允许网络安全组中的 Internet 访问。` 
->
`在网络安全组中创建入站安全规则以允许外网访问。`

2021-08-09 07:11 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
> +2. 使用默认配置创建示例配置文件，这里以 Kubernetes v1.20.4 为例。
Fix the format here.

2021-08-09 08:24 UTC, YANGMAO-ZHANG commented
Thanks for your time. I have recovered the wrong version from Git, so this is not the latest version of my translation. Really apologize for wasting your time.  I have fixed all the bugs you mentioned, and I would like to review the file again. Again, really apologize, and thanks for your patient.

2021-08-09 08:59 UTC, Felixnoo commented
> Thanks for your time. I have recovered the wrong version from Git, so this is not the latest version of my translation. Really apologize for wasting your time. I have fixed all the bugs you mentioned, and I would like to review the file again. Again, really apologize, and thanks for your patient.

No worries. Bugs are meant to be fixed by our joint efforts. Take your time.

2021-08-10 02:42 UTC, Felixnoo requested changes

2021-08-10 02:42 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
> +此外，您也可以在 Azure 实例上搭建高可用集群。本指南演示如何创建生产就绪的 Kubernetes 和 KubeSphere 群集。
`群集` -> `集群`

2021-08-10 02:42 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
> +| ssh <img width="60px"/> | TCP<img width="20px"/> | Inbound NAT<img width="30px"/> | 22<img width="60px"/> | 50200, 50201, 50202, 50100~50199<img width="10px"/> | 主节点, 普通节点 |
Delete all the `<img .../>` in this row.

2021-08-10 02:42 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
> +| ssh <img width="60px"/> | TCP<img width="20px"/> | Inbound NAT<img width="30px"/> | 22<img width="60px"/> | 50200, 50201, 50202, 50100~50199<img width="10px"/> | 主节点, 普通节点 |
`Inbound NAT` -> `入站 NAT`

2021-08-10 02:42 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
> +您可以使用 [Azure 云平台](https://azure.microsoft.com/zh-cn/overview/what-is-azure/)自行安装和管理 Kubernetes，或采用托管 Kubernetes 解决方案。如果要使用完全托管平台解决方案，请参阅 [在 AKS 上部署 KubeSphere](../../../installing-on-kubernetes/hoste
Please delete the extra spaces between `参阅` and `在` / `KubeSphere` and `。`

2021-08-10 09:31 UTC, Felixnoo commented
/lgtm

2021-08-10 10:21 UTC, Patrick-LuoYu commented
/lgtm
/approve

2021-08-10 10:22 UTC, merged