Third translation task
kubesphere/website pull request #1881
Opened 2021-08-09 16:40 UTC by YANGMAO-ZHANG

@Felixnoo 
#1854

2021-08-10 03:38 UTC, YANGMAO-ZHANG commented
I'm not sure about the translation of explantation of parameter masqueradeAll. Can you check it out? thanks.

2021-08-12 08:24 UTC, Felixnoo requested changes
Please take a look at my comments, thanks.

2021-08-12 08:24 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +     <td>是否使用 CNI 插件。KubeKey 默认安装 Calico，您也可以指定 Flannel。 请注意，只有当 Calico 被用作 CNI 插件时，才能使用某些功能，例如 Pod IP 池。</td>
`只有当 Calico 被用作 CNI 插件时` -> `只有使用 Calico 作为 CNI 插件时`
What do you think?

2021-08-12 08:24 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +       <td>用于集群启动时创建 IPv4 池的 IPIP 模式。 如果值设置除 <code>Never</code> 以外的值，则参数 <code>vxlanMode</code> 应该被设置成 <code>Never</code>。此参数允许设置值 <code>Always</code>，<code>CrossSubnet</code> 和 <code>Never</code>。默认
`如果值设置除 <code>Never</code> 以外的值` -> `如果该值不设为 <code>Never</code>`
`被设置成` -> `设为`

2021-08-12 08:24 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +       <td>用于集群启动时创建 IPv4 池的 VXLAN 模式。如果值设置除 <code>Never</code> 以外的值，则参数 <code>ipipMode</code> 应该被设置成 <code>Never</code>。此参数允许设置值 <code>Always</code>，<code>CrossSubnet</code> 和 <code>Never</code>。默认值
`如果值设置除 <code>Never</code> 以外的值` -> `如果该值不设为 <code>Never</code>`
`被设置成` -> `设为`

2021-08-12 08:24 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +     <td>设置不安全镜像 registry 的地址。 有关详细信息，请参阅{{< contentLink "https://docs.docker.com/registry/insecure/" "测试不安全 registry" >}}。</td>
` registry ` -> `仓库`

2021-08-12 08:24 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +     <td>配置专用镜像 regisry， 用于 air-gapped 安装（例如，Docker 本地 registry 或 Harbor）。 有关详细信息，请参阅{{< contentLink "docs/installing-on-linux/introduction/air-gapped-installation/" "在 Linux 安装 Air-Papped" >}}。</td>
`专用` -> `私有`
` registry ` -> `仓库`
`air-gapped` -> `离线`
`在 Linux 安装 Air-Papped` -> `离线安装`

2021-08-12 08:24 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +- `addons` 用于安装云原生加载项（YAML 或图表）。 有关详细信息，请参阅此[文件](https://github.com/kubesphere/kubekey/blob/release-1.1/docs/addons.md)。
`加载项` -> `扩展 (Addon)`
`图表` -> `Chart`

2021-08-12 08:24 UTC, Felixnoo commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +- 此页面仅列出 KubeKey 创建的配置文件中的参数的一部分。 有关其他参数的详细信息，请参阅此[示例文件](https://github.com/kubesphere/kubekey/blob/release-1.1/docs/config-example.md)。
`参数的一部分` -> `部分参数`

2021-08-15 12:42 UTC, YANGMAO-ZHANG commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +     <td>是否使用 CNI 插件。KubeKey 默认安装 Calico，您也可以指定 Flannel。 请注意，只有当 Calico 被用作 CNI 插件时，才能使用某些功能，例如 Pod IP 池。</td>
that's good, smoother than before.

2021-08-15 12:47 UTC, YANGMAO-ZHANG commented on content/zh/docs/installing-on-linux/introduction/vars.md
> +     <td>是否使用 CNI 插件。KubeKey 默认安装 Calico，您也可以指定 Flannel。 请注意，只有当 Calico 被用作 CNI 插件时，才能使用某些功能，例如 Pod IP 池。</td>
I think your translation is better because the active voice is more often used in Chinese. I will more care about this, thanks for your idea.

2021-08-16 03:28 UTC, Felixnoo commented
/lgtm

2021-08-16 03:29 UTC, Felixnoo commented
/assign @Patrick-LuoYu 
Hi, this PR is good for merging.

2021-08-31 01:26 UTC, Patrick-LuoYu commented
/lgtm
/approve

2021-08-31 01:27 UTC, merged