seventh task
kubesphere/website pull request #1970
Opened 2021-09-26 09:26 UTC by YANGMAO-ZHANG

@Felixnoo

2021-09-26 09:28 UTC, YANGMAO-ZHANG commented
#1854

2021-09-28 03:52 UTC, Felixnoo requested changes
Please take a look at the comments, thanks.

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +description: 'Learn how to use Nexus in pipelines on KubeSphere.学习如何在 KubeSphere 流水线上使用 Nexus'
`Learn how to use Nexus in pipelines on KubeSphere.学习如何在 KubeSphere 流水线上使用 Nexus`
->
`学习如何在 KubeSphere 流水线中使用 Nexus。`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +[Nexus](https://www.sonatype.com/products/repository-oss) 是存储、组织和分发工件的存储管理器。使用 Nexus 的开发者可以更好的控制开发过程中所需的工件。
`工件` -> `制品`
Matter of style.

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +本教程概述如何在 KubeSphere 流水线上使用 Nexus。
`概述` -> `演示`
`上` -> `中`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +- [GitHub](https://github.com/) 帐户。
Add `准备一个` at the beginning of this sentence.

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +- 创建一个工作空间，一个 DevOps 工程（例如，`demo-devops`）和一个帐户（例如，`project-regular`）。`project-regular` 需要被邀请至 DevOps 工程中并赋予 `operator` 角色。有关更多信息，请参考[创建企业空间、项目、帐户和角色](../../../quick-start/create-workspace-and-project
`工作空间，` -> `企业空间、`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +   - `group`：一组配置了 Nexus 的仓库。
`一组配置了 Nexus 的仓库` -> `一组已配置好的 Nexus 仓库`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +2. 在您的 **learn-pipline-java** GitHub 仓库中，点击 root 文件下的文件 `pom.xmnl`。
pom.xmnl -> pom.xml

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +3. 在文件中点击 <img src="/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/github-edit-icon.png" height="18px" /> 以修改 `<distributionManagement>` 代码片。设置 `<id>` 并使用您的 Nexus 仓库的 URL。
`代码片` -> `代码片段`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +1. 使用 `admin` 帐户登录 KubeSphere web 控制台，点击左上角的**平台**，选择**集群管理**。
`平台` -> `平台管理`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +5. 继续找到 `<mirrors>` 代码分片，然后输入一下代码：
`代码分片` -> `代码片段`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +   `<id>` 是您在步骤 2 设置给 Nexus 唯一标识符。 `<name>` 是 Nexus 仓库的名字。 `<url>` 是您 Nexus 仓库的 URL。 `<mirrorOf>` 是 要镜像的 Maven 仓库。在本教程，输入 `*` 制作所有 Maven 仓库的镜像。有关更多信息请参考[为仓库使用镜像](http://maven.apache.org/guides/mini/g
Delete the space between `是` and `要镜像`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +   `<id>` 是您在步骤 2 设置给 Nexus 唯一标识符。 `<name>` 是 Nexus 仓库的名字。 `<url>` 是您 Nexus 仓库的 URL。 `<mirrorOf>` 是 要镜像的 Maven 仓库。在本教程，输入 `*` 制作所有 Maven 仓库的镜像。有关更多信息请参考[为仓库使用镜像](http://maven.apache.org/guides/mini/g
`制作所有 Maven 仓库的镜像` -> `镜像所有 Maven 仓库`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
> +1. 登出 KubeSphere web 控制台，使用帐户 `project-regular` 登录。转到 DevOps 工程，然后在**流水线**页面点击**创建**。
`web` -> `Web`

2021-09-28 03:52 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
>     pipeline {
`https://github.com/Felixnoo/learn-pipeline-java.git` 
->
`https://github.com/YANGMAO-ZHANG/learn-pipeline-java.git`

2021-09-29 01:35 UTC, Felixnoo commented
/lgtm

2021-09-29 01:38 UTC, Felixnoo commented
/assign @Patrick-LuoYu 
Hi, this PR is submitted by the OSSC student. I reviewed it already. Please take a look at it when you are available, thanks.

2021-09-29 06:00 UTC, Patrick-LuoYu commented
/lgtm
/approve

2021-09-29 06:01 UTC, merged