eighthtask
kubesphere/website pull request #1972
Opened 2021-09-27 08:21 UTC by YANGMAO-ZHANG

2021-09-27 08:26 UTC, YANGMAO-ZHANG commented
@Felixnoo

2021-09-27 08:47 UTC, Felixnoo commented
#1854

2021-09-28 04:12 UTC, Felixnoo requested changes
Please take a look at the comments, thanks.

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +如果从远程代码仓库创建 Jenkinsfile-based 流水线，则可以在远程仓库中配置 webhook，以便对远程仓库进行改变时，自动触发流水线。
`从` -> `通过`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +- 在远程代码仓库，创建一个 Jenkinsfiel-based 流水线。有关更多信息，请参见[使用 Jenkinsfile 创建流水线](../create-a-pipeline-using-jenkinsfile/)
`在远程代码仓库，创建一个 Jenkinsfiel-based 流水线` 
->
`通过远程代码仓库创建一个基于 Jenkinsfile 的流水线`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +- 在远程代码仓库，创建一个 Jenkinsfiel-based 流水线。有关更多信息，请参见[使用 Jenkinsfile 创建流水线](../create-a-pipeline-using-jenkinsfile/)
Add `。` at the end of this sentence.

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +### 获得 webhook URL
`获得` -> `获取`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +1. 使用 `project-regular` 帐户登录 Kubesphere web 控制台。转到 DevOps 工程，点击流水线（例如，`jenkins-in-scm`）以查看详情页面。
`web` -> `Web`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +2. 点击**更多**，在下拉菜单中选择**编辑配置文件**。
`编辑配置文件` -> `编辑配置`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +3. 在出现的会话框中，滑动至 **Webhook Push** 以获得 webhook push URL。
`Webhook Push` -> `Webhook 推送`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +1. 登录您的 GitHub，并转到 `devops-java-sample` 项目。
`项目` -> `仓库`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +1. 在您仓库的**代码**页面，点击 **master** 然后选择 **sonarqube**。
**代码** -> **Code**
Let's use the UI text here.

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +2. 点击 **Recent Deliveries**，然后点击 specific delivery record 查看详情。
`specific delivery record` -> `一个具体交付记录`

2021-09-28 04:12 UTC, Felixnoo commented on content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
> +1. 使用 `project-regular` 帐户登录 Kubesphere web 控制台。转到 DevOps 工程，点击流水线。
`web` -> `Web`

2021-09-29 01:35 UTC, Felixnoo commented
/lgtm

2021-09-29 01:38 UTC, Felixnoo commented
/assign @Patrick-LuoYu 
Hi, this PR is submitted by the OSSC student. I reviewed it already. Please take a look at it when you are available, thanks.

2021-09-29 06:00 UTC, Patrick-LuoYu commented
/lgtm
/approve

2021-09-29 06:02 UTC, merged