ninth task
kubesphere/website pull request #1976
Opened 2021-09-28 15:02 UTC by YANGMAO-ZHANG

@Felixnoo

2021-09-28 15:02 UTC, YANGMAO-ZHANG commented
#1854

2021-09-29 10:08 UTC, Felixnoo requested changes
Please take a look at the comments, thanks.

2021-09-29 10:08 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +| *containerInfo.builderImage                | string   | 镜像构建器，如：kubesphere/java-8-centos7:v2.1.0. S2I。      |
Delete `S2I。`

2021-09-29 10:08 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +| containerInfo.runtimeImage                 | string   | 运行时镜像，如：kubesphere/java-8-runtime:v2.1.0. S2I。      |
`运行时镜像` -> `S2I 运行时镜像`

2021-09-29 10:08 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +| containerInfo.runtimeImage                 | string   | 运行时镜像，如：kubesphere/java-8-runtime:v2.1.0. S2I。      |
Delete `S2I。`

2021-09-29 10:08 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +| containerInfo.buildVolumes                 | []string | 关于安装卷的信息。格式为 "volume_name:mount_path", 如："s2i_java_cache:/tmp/artifacts","test_cache:test_path"]。 |
`安装卷` -> `挂载卷`

2021-09-29 10:08 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +| 制品facts.source                           | string   | 制品在镜像构建器的原始路径。                                 |
`制品facts.source` -> `containerInfo.runtimeArtifacts.source`

2021-09-29 10:08 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +| *codeFramework                             | string   | 代码框架类型，如：Java，Ruby。                               |
`，` -> `、`

2021-09-29 10:08 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +| iconPath                                   | string   | 应用名字。                                                   |
`名字` -> `名称`

2021-11-02 01:48 UTC, Felixnoo requested changes

2021-11-02 01:48 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +<<<<<<< HEAD
Please fix this conflict.

2021-11-02 01:48 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +<<<<<<< HEAD
Please fix this conflict.

2021-11-15 02:54 UTC, Felixnoo requested changes
Hi, thanks for your effort. Just one more change.

2021-11-15 02:54 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +2. 在 KubeSphere 上创建 S2I 构建时，可以找到在**环境搭建**中找到自定义 S2I 模板。
可以找到在**环境搭建**
->
可以在**构建环境**

2021-11-15 02:58 UTC, Felixnoo commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +本教程演示如何创建包含 Nginx 服务的镜像构建器。如果需要在项目中使用运行时镜像，请参阅[本文档](https://github.com/kubesphere/s2irun/blob/master/docs/runtime_image.md)以了解有关如何创建运行时镜像的更多信息。
Great catch here.

BTW, I see a lot of `映像` in this PR. I guess you used some CAT tool during translation, which is great, but you have to pay attention to the consistency of terms.

2021-11-23 02:33 UTC, YANGMAO-ZHANG commented on content/zh/docs/project-user-guide/image-builder/s2i-templates.md
> +本教程演示如何创建包含 Nginx 服务的镜像构建器。如果需要在项目中使用运行时镜像，请参阅[本文档](https://github.com/kubesphere/s2irun/blob/master/docs/runtime_image.md)以了解有关如何创建运行时镜像的更多信息。
Thanks!

2021-11-23 06:30 UTC, Felixnoo commented
/lgtm
/approve
/cc @kubesphere/sig-docs

2021-11-23 06:31 UTC, merged