fix:translate configure-webhook.md
kubesphere/website pull request #2076
Opened 2021-11-08 03:31 UTC by 123liubao

Signed-off-by: 123liubao <chenly_61@163.com>

Description：

The webhook configuration doc is missing a Chinese version.

Fix :  #2058

2021-11-08 03:32 UTC, 123liubao commented
/assign @faweizhao26

2021-11-08 06:17 UTC, Felixnoo requested changes
Hi, thanks for your contribution. I would like to request one change.

2021-11-08 06:17 UTC, Felixnoo commented on content/zh/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
> +   - 如果更改现有配置，则必须单击 **确定** 才能应用修改后的配置。
`单击` -> `点击`

2021-11-08 10:29 UTC, 123liubao commented on content/zh/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
> +   - 如果更改现有配置，则必须单击 **确定** 才能应用修改后的配置。
Done.

2021-11-08 10:31 UTC, 123liubao commented
> Hi, thanks for your contribution. I would like to request one change.

Thank you for your advice, I have modified the document.

2021-11-08 23:27 UTC, Felixnoo commented
/lgtm

2021-11-09 01:23 UTC, Felixnoo commented
/approve

2021-11-09 01:24 UTC, merged