Add a kubekey internal loadbalancer usage doc in zh docs
kubesphere/website pull request #2124
Opened 2021-11-18 05:48 UTC by 24sama

### What does this PR do?
I add a kubekey internal loadbalancer usage doc in zh docs.

/cc @FeynmanZhou

2021-12-06 08:06 UTC, FeynmanZhou commented on content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
> +title: "使用KubeKey创建高可用集群"
使用 KubeKey 内置 HAproxy 创建高可用集群

2021-12-06 08:23 UTC, FeynmanZhou commented on content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
> +keywords: 'KubeSphere, Kubernetes, KubeKey, HA, 高可用, 安装, 配置'
Please list only 5 keywords or less.

2021-12-06 08:23 UTC, FeynmanZhou commented on content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
> +linkTitle: "使用KubeKey创建高可用集群"
使用 KubeKey 内置 HAproxy 创建高可用集群

2021-12-06 08:24 UTC, FeynmanZhou commented on content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
> +description: '如何配置一个高可用 Kubernetes 集群。'
如何使用 KubeKey 内置的 HAproxy 安装一个高可用的 KubeSphere 与 Kubernetes 集群。

2021-12-06 08:24 UTC, FeynmanZhou commented on content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
> +[KubeKey](https://github.com/kubesphere/kubekey) 作为一种集群安装工具，从版本 v1.2.0 开始，提供了内置高可用模式，支持一键部署高可用集群环境。KubeKey 的高可用模式实现方式称作本地负载均衡模式。具体表现为 KubeKey 会在每一个工作节点上部署一个负载均衡器（haproxy），所有主节点的 Kubernetes 组件连接其本地的 k
haproxy => HAproxy

2021-12-06 08:28 UTC, FeynmanZhou requested changes
Please see my comments above, thanks!

2021-12-07 05:50 UTC, 24sama commented
Hi @FeynmanZhou 
Thanks for the review. I have modified it.

2021-12-09 07:14 UTC, FeynmanZhou commented
/lgtm
/approve

2021-12-09 07:15 UTC, merged