transform-traditional-applications-into-microservices
kubesphere/website pull request #2195
Opened 2021-12-15 03:42 UTC by Bettygogo2021

Signed-off-by: Bettygogo2021 <bintinggou@yunify.com>
Hi, guys. Pls kindly help me review this PR. 3ks
/assign @FeynmanZhou @JiannaLiu

2021-12-16 10:47 UTC, Felixnoo requested changes
Please see my comments, thanks.

2021-12-16 10:47 UTC, Felixnoo commented on content/en/blogs/transform-traditional-applications-into-microservices.md
> +When users are using the service mesh feature of KubeSphere, most of them merely know how to deploy the Bookinfo sample, but have no idea about how to use microservices, let alone refactor traditiona
When trying to use the service mesh features, most of KubeSphere users only manage to deploy a Bookinfo sample on KubeSphere. They are also struggling in understanding how to explore the full capabilities of service mesh, let alone refactor traditional applications into microservices.

2021-12-16 10:47 UTC, Felixnoo commented on content/en/blogs/transform-traditional-applications-into-microservices.md
> +KubeSphere microservices use the application CRD to abstract associated resources into a concrete application, and provide traffic monitoring, grayscale release, and tracing features with the help of
`However` -> `Moreover`

2021-12-16 10:47 UTC, Felixnoo commented on content/en/blogs/transform-traditional-applications-into-microservices.md
> +After the pods run properly, access the service page using the service IP address + node port. It can be seen that the application runs properly.
`using the service IP address + node port`
->
`at <Service IP address>:<Node port>`

2021-12-17 06:01 UTC, Bettygogo2021 commented
Resolved all issues. Pls help me merge this PR.

2021-12-17 06:04 UTC, Felixnoo commented
/lgtm

@FeynmanZhou 
Netlify is not functioning well. Please look into it when you are available, thanks.

2021-12-21 03:43 UTC, FeynmanZhou commented on content/en/blogs/transform-traditional-applications-into-microservices.md
> +createTime: '2021-07-07'
I prefer to use the date of the English version instead of the original publish date.

2021-12-21 03:49 UTC, FeynmanZhou commented on content/en/blogs/transform-traditional-applications-into-microservices.md
> +title: 'Refactor Traditional Applications into Microservices to Enable the Traffic Monitoring Feature'
`Transform` seems more commonly used than `Refactor ` from my investigation. `Transform` is much relevant to this blog.

2021-12-21 03:54 UTC, FeynmanZhou commented on content/en/blogs/transform-traditional-applications-into-microservices.md
> +When trying to use the service mesh features, most of KubeSphere users only manage to deploy a Bookinfo sample on KubeSphere. They are also struggling in understanding how to explore the full capabil
service mesh features => service mesh on Kubernetes

2021-12-21 06:51 UTC, Bettygogo2021 commented
Fixed issues as requested. Pls kindly help me merge the PR. 3ks.

2021-12-29 11:01 UTC, FeynmanZhou commented
/lgtm
/approve

2021-12-29 11:02 UTC, merged