Cluster Gateway Document Translation
kubesphere/website pull request #2255
Opened 2022-01-09 23:40 UTC by YANGMAO-ZHANG

@Felixnoo 
Can you please review it? Thanks.
#1854

2022-01-11 05:37 UTC, Felixnoo requested changes
Hi, thanks for your contribution! Please see my comments.

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +     - **链路追踪**：打开**链路追踪**开关以启用 KubeSphere 的链路追踪功能。功能开启后，如路由不可访问，请检查是否为路由是否添加注解（例如：`nginx.ingress.kubernetes.io/service-upstream: true`）。如注解没有添加，则添加注解至您的路由中。
`路由` -> `应用路由`

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +     - **链路追踪**：打开**链路追踪**开关以启用 KubeSphere 的链路追踪功能。功能开启后，如路由不可访问，请检查是否为路由是否添加注解（例如：`nginx.ingress.kubernetes.io/service-upstream: true`）。如注解没有添加，则添加注解至您的路由中。
（例如：`nginx.ingress.kubernetes.io/service-upstream: true`）
->
（`nginx.ingress.kubernetes.io/service-upstream: true`）

**Please help make the following update in the EN document too**:
(for example, `nginx.ingress.kubernetes.io/service-upstream: true`)
->
(`nginx.ingress.kubernetes.io/service-upstream: true`)

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +   - 为了使用链路追踪功能，请在创建组合应用程序时打开**应用治理**。
`组合应用程序` -> `自制应用`

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +   - 更多关于使用配置选项的信息，请参见 [Configuration options](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#configuration-options)。
`更多关于使用配置选项的信息` -> `有关如何使用配置选项的更多信息`

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +   同时名为 `kubesphere-router-kubesphere-system` 的网关将会创建，它作为集群中所有项目的全局网关。
同时名为 `kubesphere-router-kubesphere-system` 的网关将会创建，它作为
->
同时还创建了名为 `kubesphere-router-kubesphere-system` 的网关，作为

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +7. 创建集群网关后，有关如何创建路由的更多信息，请参见[应用路由](../../../project-user-guide/application-workloads/routes/#create-a-route)。
`创建路由` -> `创建应用路由`

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +如果在网关创建之前存在项目网关，则项目网关地址可以在集群网关地址和项目网关地址之间切换。建议您使用集群网关或项目网关。
`在网关创建` -> `在创建集群网关`

`可以在` -> `可能会在`

`您使用` -> `您只使用`

2022-01-11 05:37 UTC, Felixnoo commented on content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
> +更多关于创建项目网关的信息，请参见[项目网关](../../../project-administration/project-gateway/)。
`更多关于创建项目网关的信息` -> `关于如何创建项目网关的更多信息`

2022-01-15 19:53 UTC, YANGMAO-ZHANG commented
#2269

2022-01-17 01:48 UTC, Felixnoo commented
/lgtm
/approve

2022-01-17 01:48 UTC, merged