update description in ADD EDGE NODES
kubesphere/website pull request #2604
Opened 2022-08-01 03:18 UTC by Bettygogo2021

Signed-off-by: Bettygogo2021 <91529409+Bettygogo2021@users.noreply.github.com>
Hi, folks, I have updated the docs as suggested, pls help me review this PR. 3ks.
/assign @benjaminhuo @wenchajun

2022-08-01 09:14 UTC, Bettygogo2021 commented
I've updated the docs. For suggestions, pls leave a comment.

2022-08-02 08:24 UTC, Bettygogo2021 commented
@benjaminhuo Ben, I've updated the docs. Pls check it.

2022-08-11 05:57 UTC, benjaminhuo requested changes

2022-08-11 05:57 UTC, benjaminhuo commented on content/en/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
> +## Evict non-edge workloads
```suggestion
## Prevent non-edge workloads from being scheduled to edge nodes
```

2022-08-11 05:57 UTC, benjaminhuo commented on content/en/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
>  ## Configure an Edge Node
`## Configure an Edge Node` should be moved to a position between `## Create Firewall Rules and Port Forwarding Rules` and `## Add an Edge Node`

2022-08-11 07:49 UTC, Bettygogo2021 commented
@benjaminhuo Ben, pls check the updates.

2022-08-11 08:11 UTC, Bettygogo2021 commented
@benjaminhuo Ben, already update as suggested. Pls tag /lgtm if the updates are as expected. 3ks for your suggestions.

2022-08-11 08:23 UTC, benjaminhuo commented
/lgtm

2022-08-11 08:23 UTC, benjaminhuo commented
/approve

2022-08-11 08:25 UTC, merged