【documentation】 更新存储系统相关文档
kubesphere/website pull request #3218
Opened 2024-11-27 07:58 UTC by zhuxiujuan28

需求：https://github.com/kubesphere/project/issues/4929
文档位置：

- 安装指南 /  准备工作 /  环境要求 / 存储要求
- 安装指南 /  准备工作 /  配置外部持久化存储
- 安装指南 /  准备工作 /  配置外部持久化存储 /  配置开源存储系统

KSE  4.1.3 文档将进行同步修改

@stoneshi-yunify please review this pr

2024-11-27 08:29 UTC, stoneshi-yunify requested changes

2024-11-27 08:29 UTC, stoneshi-yunify commented on content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/01-supported-k8s.adoc
> +* {ks_product_right}的各个组件只需要存储系统提供创建/删除持久卷声明模板（PVC）的能力，不依赖扩容，克隆，快照等高级能力。
```suggestion
* {ks_product_right}的各个组件只需要存储系统提供创建、删除持久卷声明（PVC）的能力，不依赖扩容、克隆、快照等高级能力。
```

2024-11-27 08:29 UTC, stoneshi-yunify commented on content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/04-configure-external-persistent-storage/07-configure-opensource-storage.adoc
> +KubeSphere 支持众多第三方开源存储系统，包括：
```suggestion
KubeSphere 支持众多第三方开源存储系统，包括但不限于：
```

2024-11-27 08:29 UTC, stoneshi-yunify commented on content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/04-configure-external-persistent-storage/07-configure-opensource-storage.adoc
> +* ... 等等
```suggestion
等
```

2024-11-27 08:29 UTC, stoneshi-yunify commented on content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/04-configure-external-persistent-storage/07-configure-opensource-storage.adoc
> +若要在{ks_product_both}平台安装第三方开源存储系统，请到存储系统的官方网站进行下载安装。
```suggestion
{ks_product_both} 不提供第三方开源存储系统的安装包，请到存储系统的官方网站下载安装。
```

2024-11-27 09:31 UTC, zhuxiujuan28 commented
中文修改完毕，英文已同步翻译
@stoneshi-yunify please review and merge it

2024-11-27 09:45 UTC, stoneshi-yunify commented
/lgtm

2024-11-27 09:48 UTC, stoneshi-yunify commented
/approve

2024-11-27 09:49 UTC, stoneshi-yunify commented
cc @zheng1 , pls merge it

2024-12-09 06:18 UTC, zhuxiujuan28 commented
/assign @zheng1 please merge it

2024-12-09 06:51 UTC, zheng1 commented
/approve

2024-12-09 06:51 UTC, merged