update manifests url
kubesphere/website pull request #414
Opened 2020-10-30 01:06 UTC by pixiake

Signed-off-by: pixiake <guofeng@yunify.com>

2020-10-30 05:05 UTC, Sherlock113 commented
/lgtm

2020-10-31 13:07 UTC, rayzhou2017 requested changes
/cc @pixiake please resolve the conflicts.

2020-10-31 13:42 UTC, pixiake commented
Signed-off-by: pixiake guofeng@yunify.com

2020-10-31 14:00 UTC, rayzhou2017 approved these changes
/lgtm

2020-10-31 14:37 UTC, merged