Update multicluster app deployment using jenkinsfile
kubesphere/website pull request #472
Opened 2020-11-05 14:00 UTC by Sherlock113

Signed-off-by: Sherlock113 <sherlockxu@yunify.com>

2020-11-06 07:40 UTC, yuswift requested changes

2020-11-06 07:40 UTC, yuswift commented on content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
> +You need to create credentials in KubeSphere for the access token created so that the pipeline can interact with Docker Hub for imaging pushing. Besides, you also create kubeconfig credentials for th
`you also need to create ` may be better?
@Sherlock113

2020-11-06 07:40 UTC, yuswift commented on content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
> +       // for more member clusters, please manifest/multi-cluster-deploy.yaml
please edit manifest/multi-cluster-deploy.yaml

2020-11-06 07:42 UTC, yuswift commented
BTW, you can use `git rebase` to merge multiple commits into one finally, which can reduce the commits on master.

2020-11-09 02:02 UTC, yuswift commented
/lgtm

2020-11-09 06:51 UTC, yuswift commented
/lgtm

2020-11-09 08:12 UTC, rayzhou2017 approved these changes

2020-11-09 08:12 UTC, merged