Add a blog for using kubekey to add master nodes for HA
kubesphere/website pull request #998
Opened 2021-01-21 08:39 UTC by Sherlock113

Signed-off-by: Sherlock113 <sherlockxu@yunify.com>

2021-01-21 08:49 UTC, FeynmanZhou requested changes

2021-01-21 08:49 UTC, FeynmanZhou commented on content/en/blogs/add-master-for-ha-using-kubekey.md
> +You can use any cloud load balancers or hardware load balancers (e.g. F5). In this example, I have an internal load balancer with a listener that listens on port `6443` (`api-server`) and an external
Ref: https://kubesphere.com.cn/forum/d/1566-kubernetes-keepalived-haproxy

2021-01-21 08:58 UTC, Sherlock113 commented on content/en/blogs/add-master-for-ha-using-kubekey.md
> +You can use any cloud load balancers or hardware load balancers (e.g. F5). In this example, I have an internal load balancer with a listener that listens on port `6443` (`api-server`) and an external
I just have one question: 
![40401611219409_ pic](https://user-images.githubusercontent.com/65327072/105327495-e7e5f300-5c09-11eb-8aaa-07fe49f13060.jpg)
So the Porter doc is incorrect here?

2021-01-21 09:30 UTC, Sherlock113 commented on content/en/blogs/add-master-for-ha-using-kubekey.md
> +You can use any cloud load balancers or hardware load balancers (e.g. F5). In this example, I have an internal load balancer with a listener that listens on port `6443` (`api-server`) and an external
I will add the example of using keepalived and haproxy in another blog.

2021-01-21 09:30 UTC, FeynmanZhou commented on content/en/blogs/add-master-for-ha-using-kubekey.md
> +You can use any cloud load balancers or hardware load balancers (e.g. F5). In this example, I have an internal load balancer with a listener that listens on port `6443` (`api-server`) and an external
I think we have clarified its concepts.

2021-01-21 10:02 UTC, Sherlock113 commented on content/en/blogs/add-master-for-ha-using-kubekey.md
> +You can use any cloud load balancers or hardware load balancers (e.g. F5). In this example, I have an internal load balancer with a listener that listens on port `6443` (`api-server`) and an external
Already changed.

2021-01-24 14:00 UTC, FeynmanZhou commented on content/en/blogs/add-master-for-ha-using-kubekey.md
> +You can use any cloud load balancers or hardware load balancers (e.g. F5). In this example, I have an internal load balancer with a listener that listens on port `6443` (`api-server`) and an external
> I will add the example of using keepalived and haproxy in another blog.

ok.

2021-01-24 14:36 UTC, FeynmanZhou approved these changes

2021-01-24 14:36 UTC, FeynmanZhou commented
/lgtm

2021-01-24 14:37 UTC, merged